num1 = int(input("Enter first number  : "))
num2 = int(input("Enter second number :"))
print(str(num1) + " + " + str(num2) + " = " + str(num1+num2))
print(str(num1) + " - " + str(num2) + " = " + str(num1-num2))
print(str(num1) + " * " + str(num2) + " = " + str(num1*num2))
print(str(num1) + " / " + str(num2) + " = " + str(int(num1/num2)))