SF = float(10)
SG = float(20)
SI = float(30)
SC = float(50)

print("---Your Score---")
print("Foundation English               :", SF)
print("General Business                 :", SG)
print("Introduction to Computer Systems :", SI)
print("Computer Programming             :", SC)